<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \User\Form\SignUp $form
 * @var bool $failure
 */
$this->headTitle('Sign In');
$inputLogin = $form->get('login');
?>
<div class="container">
    <div class="page-header">
        <h1><?=$this->translate('Sign In')?></h1>
    </div>
    <? if($failure): ?>
    <div class="alert alert-danger">
        <strong><?=$this->translate('Error')?>!</strong> <?=$this->translate('Incorrect login or password')?>
    </div>
    <? endif; ?>
    <div class="well">
        <?=$this->tbForm()->openTag($form)?>
        <?=$this->tbFormCollection($form)?>

        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="submit" class="btn btn-primary"><?=$this->translate('Sign In');?></button>
                <a class="btn btn-link" href="<?=$this->url('user/signup')?>"><?=$this->translate('Sign Up');?></a>
            </div>
        </div>
        <?=$this->tbForm()->closeTag($form)?>
    </div>
</div>
