<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \User\Form\SignUp $form
 * @var string|boolean $alert
 */
$this->headTitle('Sign Up');
?>
<div class="container">
    <div class="page-header">
        <h1><?=$this->translate('Sign Up')?></h1>
    </div>
    <div class="well">
        <? if($alert !== false): ?>
        <div class="alert alert-danger">
            <strong>Warning!</strong> <?=$alert?>
        </div>
        <? endif; ?>
        <?=$this->TBForm()->openTag($form)?>
        <?=$this->TBFormCollection($form, true)?>

        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="submit" class="btn btn-primary"><?=$this->translate('Sign Up');?></button>
                <a class="btn btn-link" href="<?=$this->url('user/signin')?>"><?=$this->translate('Sign In');?></a>
            </div>
        </div>
        <?=$this->TBForm()->closeTag($form)?>
    </div>
</div>
