<?php
/**
 * User: Igor Bubnevich aka Indrig
 * Date: 14.08.13
 * Time: 17:58
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \User\Form\SignUp $form
 */
$this->headTitle('Sign In');

?>
<div class="container">
    <div class="page-header">
        <h1><?=$this->translate('Sign In')?></h1>
    </div>
    <div class="well">
        <?=$this->TBForm()->openTag($form, \TwitterBootstrap\Form\Form::FORM_TYPE_HORIZONTAL)?>
        <?=$this->TBFormCollection($form, true, \TwitterBootstrap\Form\Form::FORM_TYPE_HORIZONTAL)?>

        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-9">
                <button type="submit" class="btn btn-primary"><?=$this->translate('Sign In');?></button>
                <a class="btn btn-link" href="<?=$this->url('user/signup')?>"><?=$this->translate('Sign Up');?></a>
            </div>
        </div>
        <?=$this->TBForm()->closeTag($form)?>
    </div>
</div>
