<?php
/**
 * User: Igor Bubnevich aka Indrig
 * Date: 14.08.13
 * Time: 17:58
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \User\Form\SignUp $form
 * @var string|boolean $alert
 */
$this->headTitle('Sign Up');
?>
<div class="container">
    <div class="panel">
        <div class="panel-heading"><h1 class="panel-title"><?=$this->translate('Sign Up')?></h1></div>
        <div class="panel-body">
            <? if($alert !== false): ?>
            <div class="alert alert-danger">
                <strong>Warning!</strong> <?=$alert?>
            </div>
            <? endif; ?>
            <?=$this->TBForm()->openTag($form, \TwitterBootstrap\Form\Form::FORM_TYPE_HORIZONTAL)?>
            <?=$this->TBFormCollection($form, true, \TwitterBootstrap\Form\Form::FORM_TYPE_HORIZONTAL)?>

            <div class="form-group">
                <div class="col-lg-offset-3 col-lg-9">
                    <button type="submit" class="btn btn-primary"><?=$this->translate('Sign Up');?></button>
                    <a class="btn btn-link" href="<?=$this->url('user/signin')?>"><?=$this->translate('Sign In');?></a>
                </div>
            </div>
            <?=$this->TBForm()->closeTag($form)?>
        </div>
    </div>
</div>
