<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $content
 * @var \User\Adapter\Authentication $user
 */
?>
<?=$this->doctype()?>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?=$this->headTitle()->setSeparator(' - ')->setAutoEscape(false)?>

        <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

        <?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.css') ?>

        <?=$this->headScript()->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')->prependFile($this->basePath() . '/assets/js/jquery.min.js') ?>

    </head>
    <body>

    <? if(!$this->user()->isLogin()): ?>
    <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="form-horizontal" method="post" action="<?=$this->url('user/signin')?>">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?=$this->translate('Sign In')?></h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputLogin" class="col-lg-2 control-label"><?=$this->translate('Login')?></label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" id="inputLogin" name="login"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="col-lg-2 control-label"><?=$this->translate('Password')?></label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" id="inputPassword" name="password"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <div class="checkbox">
                                <label>
                                    <input name="quick_expire" type="checkbox" value="1" /><?=$this->translate('Do not remember me')?>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="<?=$this->url('user/signup')?>" class="btn btn-default"><?=$this->translate('Sign Up')?></a>
                    <button type="submit" class="btn btn-primary"><?=$this->translate('Sign In')?></button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <? endif; ?>

        <div id="wrap">
            <nav class="navbar navbar-inverse" id="navbar-main" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main-collapse">
                            <span class="sr-only"><?=$this->translate('Toggle navigation')?></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?=$this->url('home')?>"><?=$this->escapeHTML($this->headTitle()->offsetGet(0))?></a>
                    </div>

                    <div class="collapse navbar-collapse" id="navbar-main-collapse">
                        <ul class="nav navbar-nav">
                            <?=$this->Navigation('navigation')
                                ->menu()
                                ->setMinDepth(0)
                                ->setMaxDepth(1)
                                ->render();?>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <? if($this->user()->isLogin()): ?>
                                <li class="dropdown">
                                    <a href="" class="dropdown-toggle" data-toggle="dropdown"><?=$this->user()->screenName()?> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?=$this->url('user')?>"><?=$this->translate('Profile')?></a></li>
                                        <li><a href="<?=$this->url('user/signout')?>"><?=$this->translate('Sign Out')?></a></li>
                                    </ul>
                                </li>
                            <? else: ?>
                                <li><button data-toggle="modal" class="btn navbar-btn btn-success" data-toggle="modal" data-target="#signInModal"><span class="icon-user"></span> <?=$this->translate('Sign In')?></button></li>
                            <? endif; ?>
                        </ul>
                    </div>
                </div>

            </nav>
            <?=$content?>
            <div id="push"></div>
        </div>
        <div id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">&copy; <?=date('Y')?> Indrig Soft</div>
                    <div class="col-md-3">
                                           </div>
                    <div class="col-md-3">
                                          </div>
                    <div class="col-md-3">
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
