<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $content
 * @var \User\Adapter\Authentication $user
 */

echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('АнтиКафе "ЧАС ПИК"')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()//->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/assets/js/jquery.min.js') ?>

    </head>
    <body>
    <? /*
    <? if(!$this->user()->isLogin()): ?>
    <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="form-horizontal" method="post" action="<?=$this->url('user/signin')?>">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?=$this->translate('Sign In')?></h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputLogin" class="col-lg-2 control-label"><?=$this->translate('Login')?></label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" id="inputLogin" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="col-lg-2 control-label"><?=$this->translate('Password')?></label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" id="inputPassword" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <div class="checkbox">
                                <label>
                                    <input name="not_remember" type="checkbox" value="1" /><?=$this->translate('Do not remember me')?>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="<?=$this->url('user/signup')?>" class="btn btn-default"><?=$this->translate('Sign Up')?></a>
                    <button type="submit" class="btn btn-primary"><?=$this->translate('Sign In')?></button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <? endif; ?>
 */?>
        <div id="wrap">
            <nav class="navbar navbar-inverse" id="navbar-main" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main-collapse">
                        <span class="sr-only"><?=$this->translate('Toggle navigation')?></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand" href="/">ЧАС ПИК</div>
                </div>

                <div class="collapse navbar-collapse" id="navbar-main-collapse">
                    <ul class="nav navbar-nav">
                        <?=$this->Navigation('Navigation')
                            ->menu()
                            ->setPartial('partial/navbar')
                            ->setMinDepth(0)
                            ->setMaxDepth(1)
                            ->render();?>
                    </ul>
                    <? /*
                    <ul class="nav navbar-nav navbar-right">
                        <? if(!$this->user()->isLogin()): ?>
                        <li><button data-toggle="modal" class="btn navbar-btn btn-success" data-toggle="modal" data-target="#signInModal"><span class="icon-user"></span> <?=$this->translate('Sign In')?></button></li>
                        <? endif; ?>
                    </ul>*/?>
                </div>
            </nav>
            <?=$content?>
            <div id="push"></div>
        </div>
        <div id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 visible-md">&copy; <?=date('Y')?> Indrig Soft</div>
                    <div class="col-md-3 visible-md">
                        <strong>Ссылки</strong><br />
                        <a href="http://vk.com/ak_chas_pik" target="_blank" a><img src="/assets/img/social/vkontakte.png" alt="ВКонтакете" width="24" height="24" /></a>
                    </div>
                    <div class="col-md-3 visible-md">
                        <strong>Режим работы</strong><br />
                        <ul class="list-unstyled">
                        <li>Пн - Чт с 15.00 до 22.00</li>
                        <li>Пт с 15.00 до последнего посетителя.</li>
                        <li class="text-danger">Сб и Вс с 12.00 до последнего</li>
                        </ul>
                    </div>
                    <address class="col-md-3 text-right">
                            <strong>Антикафе &rdquo;ЧАС ПИК&rdquo;</strong><br />
                            пр. Санкт петербургский  д. 12<br />
                            Санкт-Петербург, Россия<br />
                            <abbr title="Телефон">Т:</abbr> +7 (981) 768-51-10
                    </address>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
