<? if($modal): ?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><?=$name?> <small><?=$this->translate('Install')?></small></h4>
        </div>
        <div class="modal-body">
            <p>One fine body&hellip;</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('Cancel')?></button>
            <button type="button" class="btn btn-primary"><?=$this->translate('Install')?></button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
<? else: ?>
    <div class="container">
        <div class="page-header">
            <h1 class="modal-title"><?=$name?> <small><?=$this->translate('Install')?></small></h1>
        </div>
    </div>
<? endif; ?>