<?php
/**
 * @var string $htmlOptions
 */
?>
<div class="container">
    <div class="page-header">
        <h1 class="modal-title"><?=$module?> <small><?=$this->translate('Uninstall')?></small></h1>
    </div>
    <form method="post" action="<?=$this->url('admin/module', array('action' => 'uninstall', 'module' => $module))?>">
        <div class="panel panel-default">
            <div class="panel-body">
                <? if($error): ?>
                    <div class="alert alert-danger">
                        <?=$this->translate('Module install error')?>
                    </div>
                <? endif; ?>
                <?=$htmlOptions?>
            </div>
            <div class="btn-toolbar text-right">
                <input type="hidden" name="uninstall" value="1" />
                <a href="<?=$this->url('admin/module')?>" class="btn btn-default"><?=$this->translate('Cancel')?></a>
                <button type="submit" class="btn btn-danger"><?=$this->translate('Uninstall')?></button>
            </div>
        </div>
    </form>
</div>