<div class="container">
    <div class="page-header">
        <h1><?=$this->translate('Edit')?> <small><?=$this->escapeHTML($user->screenName())?></small></h1>
    </div>

    <?=$this->navigation('Navigation')->breadcrumbs(); ?>
    <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="#user" data-toggle="tab"><?=$this->translate('User')?></a></li>
        <li class=""><a href="#role" data-toggle="tab"><?=$this->translate('Roles')?></a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="user">

        </div>
        <div class="tab-pane fade" id="role">

        </div>
        <div class="btn-toolbar">
            <button class="btn btn-primary" type="submit"><?=$this->translate('Save')?></button>
        </div>
    </div>

</div>