<div class="container">
    <div class="page-header">
        <h1><?=$this->translate('Users')?></h1>
    </div>
    <button type="button" class="btn btn-success">Create</button>
    <table class="table well">
        <tr>
            <th></th>
            <th>#</th>
            <th>Name</th>
        </tr>
        <? foreach($list as $item): ?>
            <tr>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn">Edit</button>
                        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="<?=$this->url('user/admin/edit', array('id' => $item->id))?>">Edit</a></li>
                            <li><a href="#">Delete</a></li>
                        </ul>
                    </div>
                </td>
                <td><?=$item->id?></td>
                <td><?=$this->escapehtml($item->login)?></td>
            </tr>
        <? endforeach; ?>
    </table>
</div>