<div class="container">
    <div class="page-header">
        <h1><?=$this->translate('Roles')?> <small><?=$this->translate('Edit')?></small></h1>
    </div>

    <?=$this->navigation('Navigation')->breadcrumbs(); ?>

    <div class="btn-toolbar">
        <div class="row">
            <div class="col-lg-12">
                <a href="<?=$this->url('user/admin/role/create')?>" class="btn btn-primary"><?=$this->translate('Create')?></a>
            </div>
        </div>
    </div>

    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>#</th>
            <th><?=$this->translate('Name')?></th>
            <th><?=$this->translate('Actions')?></th>
        </tr>
        <? foreach($roles as $role): ?>
            <tr>
                <td><?=$role->id?></td>
                <td><?=$this->escapehtml($role->name)?></td>
                <td><a href="<?=$this->url('user/admin/role/edit', array('id' => $role->id))?>" class="btn btn-default"><?=$this->translate('Edit')?></a> </td>
            </tr>
        <? endforeach; ?>
    </table>
</div>