<div class="container">
    <div class="page-header">
        <h1><?=$this->translate('Roles')?></h1>
    </div>
    <button type="button" class="btn btn-success">Create</button>
    <table class="table well">
        <tr>
            <th>#</th>
            <th>Name</th>
        </tr>
        <? foreach($roles as $role): ?>
            <tr>
                <td><?=$role->id?></td>
                <td><?=$this->escapehtml($role->name)?></td>
            </tr>
        <? endforeach; ?>
    </table>
</div>