<?php
/**
 * @var \Main\Form\UserLogin $form
 */
?>
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Error</h3>
    </div>
    <?=$form?>

        <form class="form-horizontal">
            <div class="form-group">
                <label for="inputEmail" class="col-lg-4 control-label">Email</label>
                <div class="col-lg-4">
                    <input name="login" type="text" class="form-control" id="inputLogin" placeholder="Email" required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword" class="col-lg-4 control-label">Password</label>
                <div class="col-lg-4">
                    <input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password" required="required">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> Remember me
                        </label>
                    </div>
                    <button type="submit" class="btn btn-default">Sign in</button>
                </div>
            </div>
        </form>

</div>