<?php
/**
 * @var $page Zend\Navigation\Page\Mvc
 * @var $container Zend\Navigation\Navigation

 */
?>
<ul class="nav navbar-nav">
<? foreach ($this->container as $page): ?>

        <? if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <? if( ! $page->hasPages()): ?>
            <li<?=$page->isActive() ? ' class="active"' : ''?>><a href="<?=$page->getHref()?>"><?=$this->translate($page->getLabel())?></a></li>
        <? else: ?>
            <li class="dropdown<?=$page->isActive(true) ? ' active' : ''?>">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <?php echo $this->translate($page->getLabel()) ?> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <?php foreach($page->getPages() as $child): ?>
                        <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                        <li<?=$child->isActive(true) ? ' class="active"' : ''?>>
                            <a href="<?=$child->getHref() ?>">
                                <?=$this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </li>
        <? endif ?>

    <? endforeach ?>
</ul>