<?php
/**
 * @var $message
 * @var $file
 * @var $line
 * @var $backtrace
 */
?>
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Error</h3>
    </div>
    <div class="alert alert-danger">
        <p><strong>Message:</strong> <?=$message?></p>
        <p><strong>File:</strong> <?=$file?></p>
        <p><strong>Line:</strong> <?=$line?></p>
    </div>
    <ul class="list-group">
    <? foreach($backtrace as $trace): ?>
        <li class="list-group-item">
            <span class="badge"><?=empty($trace['line']) ? '--' : $trace['line']?></span>
            <p>
                <?=empty($trace['file']) ? 'Unknown file' : $trace['file']?>
            </p>
            <p>
                <? if(isset($trace['class'])): ?>
                    In class <?=$trace['class']?>::<?=$trace['function']?>
                <? elseif(isset($trace['function'])): ?>
                    In function <?=$trace['function']?>
                <? endif; ?>

            </p>
        </li>
    <? endforeach; ?>
    </ul>
</div>
