<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $content
 * @var \User\Adapter\Authentication $user
 */
?>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Internal error</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <script language="javascript" src="/assets/js/jquery.min.js"></script>
    <script language="javascript" src="/assets/js/bootstrap.min.js"></script>
</head>
<body>



<div id="wrap">

    <div class="container">
        <div class="page-header">
            <h1>Internal error</h1>
        </div>
        <div class="alert alert-danger">
            Server internal error. Pleas try letter.
        </div>
    </div>
    <div id="push"></div>
</div>
<div id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-3">&copy; <?=date('Y')?> Indrig Soft</div>
            <div class="col-md-3">
            </div>
            <div class="col-md-3">
            </div>
            <div class="col-md-3">
            </div>
        </div>
    </div>
</div>
</body>
</html>
