<div id="carousel-captions" class="carousel slide bs-docs-carousel">
    <ol class="carousel-indicators">
        <li data-target="#carousel-captions" data-slide-to="0" class=""></li>
        <li data-target="#carousel-captions" data-slide-to="1" class=""></li>
        <li data-target="#carousel-captions" data-slide-to="2" class="active"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item" style="background-image: url('/assets/img/home/carousel/slide1.jpg')">

            <div class="carousel-caption">
                <h3>First slide label</h3>
                <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            </div>
        </div>
        <div class="item" style="background-image: url('/assets/img/home/carousel/slide1.jpg')">

            <div class="carousel-caption">
                <h3>Second slide label</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
        </div>
        <div class="item active" style="background-image: url('/assets/img/home/carousel/slide1.jpg')">

            <div class="carousel-caption">
                <h3>Third slide label</h3>
                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#carousel-captions" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#carousel-captions" data-slide="next">
        <span class="icon-next"></span>
    </a>
</div>
<div class="container">
    <?=$this->table();?>
</div>